/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CurrentTemp: typeof import('./src/components/CurrentWeather/CurrentTemp.vue')['default']
    CurrentWind: typeof import('./src/components/CurrentWeather/CurrentWind.vue')['default']
    ForecastTable: typeof import('./src/components/5Day3HrWeather/ForecastTable.vue')['default']
    Image: typeof import('primevue/image')['default']
    LocationSelector: typeof import('./src/components/LocationSelector.vue')['default']
    SunInformation: typeof import('./src/components/CurrentWeather/SunInformation.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    V2EditRow: typeof import('./src/components/5Day3HrWeather/V2EditRow.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
  }
}
